name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  actionlint:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/actionlint.yml@eaff82d53231c122639cff2f7682765191fc05f7 # main

  spellcheck:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/spellcheck.yml@eaff82d53231c122639cff2f7682765191fc05f7 # main
